### ISSUE TITLE
Variáveis quebradas

### ISSUE THREAD

**Issue by viniciuscaol** [Ar3secchim/infra-terraform#2]
Bom dia Renara, fui testar seu código para vê quantos recursos ele sobe para comparar com o meu e quando rodei suas variáveis estão sem valor default. Possivelmente você setou no .terraform ou no tfvars que não veio para o git, dá uma olhada la depois.

**Comment by Ar3secchim** [comment]
Sim, a professora disse que por boas práticas melhor colocar e um arquivo separado. Por isso que não tem default.  

Em Terraform, uma boa prática é definir variáveis de maneira que você possa customizar os valores ao usar o código em ambientes diferentes. 
Acabei decidindo usar  variáveis e defini-las claramente em diferentes arquivos (.tfvars, por exemplo) para cada ambiente (produção, desenvolvimento, teste) é uma prática recomendada. Com isso, o mesmo código pode ser reutilizado em vários ambientes mudando apenas os arquivos de configuração. Isso facilita a manutenção, pois o código permanece o mesmo, mas os valores (como IDs, IPs, etc.) podem ser ajustados conforme o ambiente.
